inherit_from: .rubocop_todo.yml

AllCops:
  DisabledByDefault: true

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false
